### ISSUE TITLE
io.UnsupportedOperation: fileno

### ISSUE THREAD

**Issue by nijaaam** [Rediker-Software/django-azure-storage#12]
I am gettings this exeception when running `python manage.py dbrestore`

```python
Restoring: default-jamun-g-Inspiron-3542-2017-01-23-151908.dump
Restore tempfile created: 1.9 KiB
Are you sure you want to continue? [Y/n] y
Raw content
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 54, in handle
    self._restore_backup()
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/management/commands/dbrestore.py", line 94, in _restore_backup
    self.connector.restore_dump(input_file)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/db/base.py", line 96, in restore_dump
    result = self._restore_dump(dump)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/db/mysql.py", line 39, in _restore_dump
    stdout, stderr = self.run_command(cmd, stdin=dump, env=self.restore_env)
  File "/usr/local/lib/python2.7/dist-packages/dbbackup/db/base.py", line 145, in run_command
    env=full_env)
  File "/usr/lib/python2.7/subprocess.py", line 702, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 1118, in _get_handles
    p2cread = stdin.fileno()
io.UnsupportedOperation: fileno
```

**Comment by kevin-brown** [comment]
It looks like this is an issue in the django-dbbackup package. I'd recommend posting this bug report at their repository instead.

https://github.com/django-dbbackup/django-dbbackup
